### ISSUE TITLE
Plottling functions

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/solar-and-storage#1]
Wrap plotting functions into the Optimization object. This will make it really easy and visualize the optimization results

**Comment by gilbertgong** [comment]
https://github.com/openclimatefix/solar-and-storage/pull/3

**Comment by gilbertgong** [comment]
This should probably be closed - I didn't understand how the "Fixes #" in the PR worked when I submitted it..

**Comment by peterdudfield** [comment]
Yes, it doesnt sometimes, but not sometimes.

**Comment by peterdudfield** [comment]
@all-contributors please add @peterdudfield  for code

**Comment by peterdudfield** [comment]
@all-contributors please add @gilbertgong  for code
